baseURL = "https://skkuding.dev"
languageCode = 'ko-kr'
title = 'SKKUDING ìŠ¤ê¾¸ë”©'

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"

[params]
color = 'gray'
github = 'skkuding'
description = 'ì„±ê· ê´€ëŒ€í•™êµ ì½”ë“œë‹¹ í”„ë¡œì íŠ¸ íŒ€ ìŠ¤ê¾¸ë”©'
images = ['open-graph.png']
title = 'SKKUDING ìŠ¤ê¾¸ë”©'
avatar = 'skkuding@gmail.com'
name = 'ìš°ë¦¬ëŠ” ìŠ¤ê¾¸ë”©ì´ì—ìš”! ğŸ‘‹'
bio = 'ì„±ê· ê´€ëŒ€í•™êµ ì½”ë“œë‹¹ í”„ë¡œì íŠ¸ íŒ€'

[menu]
[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "https://pf.kakao.com/_UKraK"

[deployment]
[[deployment.targets]]
name = 'AWS S3'
URL = 's3://skkuding.dev?region=ap-northeast-2'
